---
driver:
  name: vagrant

  network:
    - ["private_network", {ip: "33.33.33.33"}]

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-6.7

suites:
  - name: default
    run_list:
      - recipe[ea_httpd::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
