name 'ea_httpd'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures ea_httpd'
long_description 'Installs/Configures ea_httpd'
version '0.1.0'
